# Generated by Django 4.2 on 2023-04-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField()),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('habitacion_nro', models.IntegerField()),
                ('habitacion_disponible', models.CharField(max_length=3)),
                ('fecha_salida', models.DateField()),
            ],
        ),
    ]
